apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATIONNAME}-secret-template
  annotations:
    description: "${APPLICATIONNAME} secret template"
    tags: "azure-agent"
parameters:
- description: Name of the application
  name: APPLICATIONNAME
  value: azure-devops-agent
- description: Azure DevOps Agent PAT
  name: AZP_TOKEN
  required: true
objects:  
- apiVersion: v1
  stringData:
    AZP_TOKEN: ${AZP_TOKEN}
  kind: Secret
  metadata:
    name: ${APPLICATIONNAME}
  type: Opaque