apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATIONNAME}-configmap-template
  annotations:
    description: "${APPLICATIONNAME} configmap template"
    tags: "azure-agent"
parameters:
- description: Name of the application
  name: APPLICATIONNAME
  value: azure-devops-agent
- description: Azure DevOps instance
  name: AZP_URL
  required: true  
- description: Azure DevOps Pool name
  name: AZP_POOL
  required: true
  value: ""
objects:
- apiVersion: v1
  data:
    AZP_URL: ${AZP_URL}
    AZP_POOL: ${AZP_POOL}
  kind: ConfigMap
  metadata:
    name: ${APPLICATIONNAME}