apiVersion: v1
kind: Template
metadata:
  name: ${APPLICATIONNAME}-configmap-template
  annotations:
    description: "${APPLICATIONNAME} configmap template"
    tags: "azure-agent"
parameters:
- description: Name of the application
  name: APPLICATIONNAME
  value: azure-devops-agent
- description: Azure DevOps instance
  name: AZP_URL
  required: true  
- description: Azure DevOps Pool name
  name: AZP_POOL
  required: true
  value: ""
- description: Capablitities
  name: AZP_CAPABILITY_ENV_VARS
  value: ""
- description: Agent download url
  name: AZP_AGENT_PACKAGE_LATEST_URL
  value: ""
objects:
- apiVersion: v1
  data:
    AZP_URL: ${AZP_URL}
    AZP_POOL: ${AZP_POOL}
    AZP_CAPABILITY_ENV_VARS: ${AZP_CAPABILITY_ENV_VARS}
    AZP_AGENT_PACKAGE_LATEST_URL: ${AZP_AGENT_PACKAGE_LATEST_URL}
  kind: ConfigMap
  metadata:
    name: ${APPLICATIONNAME}